@McpServer_HostAddress = http://localhost:5000

GET {{McpServer_HostAddress}}/status
Accept: application/json

###

POST {{McpServer_HostAddress}}/
Content-Type: application/json

{
  "jsonrpc": "2.0",
  "method": "ping",
  "id": 1
}

###
